name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Run Integration Tests
        run: npm run test:integration

  deploy:
    name: Deploy to AWS EC2
    runs-on: self-hosted
    needs: test  # Ensures tests pass before deployment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-docker-app .

      - name: Stop and Remove Old Container
        run: |
          docker stop my-docker-container || true
          docker rm my-docker-container || true

      - name: Run New Container
        run: docker run -d -p 8080:80 --name my-docker-container my-docker-app
